import React from "react";

type TileType = "TW" | "DW" | "TL" | "DL" | "CENTER" | "NORMAL";

const BOARD_LAYOUT: TileType[][] = [
  [
    "TW",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "TW",
  ],
  [
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
  ],
  [
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
  ],
  [
    "DL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "DL",
  ],
  [
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
  ],
  [
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
  ],
  [
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
  ],
  [
    "TW",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "CENTER",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "TW",
  ],
  [
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
  ],
  [
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
  ],
  [
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
  ],
  [
    "DL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "DL",
  ],
  [
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
  ],
  [
    "NORMAL",
    "DW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DW",
    "NORMAL",
  ],
  [
    "TW",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "TW",
    "NORMAL",
    "NORMAL",
    "NORMAL",
    "DL",
    "NORMAL",
    "NORMAL",
    "TW",
  ],
];

const TILE_LABELS: Record<TileType, string> = {
  TW: "TW",
  DW: "DW",
  TL: "TL",
  DL: "DL",
  CENTER: "★",
  NORMAL: "",
};

const TILE_STYLES: Record<TileType, string> = {
  TW: "bg-[#d3443a] text-white",
  DW: "bg-[#f09c85] text-[#111]",
  TL: "bg-[#3f65b8] text-white",
  DL: "bg-[#96c4d8] text-[#111]",
  CENTER: "bg-[#d9945b] text-[#111]",
  NORMAL: "bg-[#1e5a32]",
};

const TILE_DESCRIPTION: Record<TileType, string> = {
  TW: "Triple Word",
  DW: "Double Word",
  TL: "Triple Letter",
  DL: "Double Letter",
  CENTER: "Starting star",
  NORMAL: "Normal",
};

export function ScrabbleBoard() {
  return (
    <div className="w-full max-w-[min(95vw,650px)]">
      <div className="grid grid-cols-[repeat(15,minmax(0,1fr))] overflow-hidden rounded-2xl border-4 border-stone-400 bg-stone-300 shadow-xl">
        {BOARD_LAYOUT.map((row, rowIndex) =>
          row.map((tile, colIndex) => (
            <div
              key={`${rowIndex}-${colIndex}`}
              className={`aspect-square border border-stone-300 text-[0.6rem] font-semibold uppercase tracking-wide flex items-center justify-center ${TILE_STYLES[tile]}`}
              aria-label={`${TILE_DESCRIPTION[tile]} square (${rowIndex + 1}, ${colIndex + 1})`}
            >
              {TILE_LABELS[tile]}
            </div>
          )),
        )}
      </div>
    </div>
  );
}

export default ScrabbleBoard;
